#!/bin/bash
while read X; do
message=$X
length=${#message}
backward=""
for ((i=$length-1; i>=0; i--)); do
    backward=$backward${message:$i:1}
done
if [ "${message,,}" == "${backward,,}" ]; then echo $message
fi
done
